builder:
  track: dev

labels:
  team: estafette-team
  language: docker

pipelines:
  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette
    tags:
    - ${ESTAFETTE_GIT_BRANCH}