builder:
  track: dev

labels:
  team: estafette-team
  language: docker

stages:
  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - europe-docker.pkg.dev/travix-com/eu-docker-travix
    expand-variables: false

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - europe-docker.pkg.dev/travix-com/eu-docker-travix

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - europe-docker.pkg.dev/travix-com/eu-docker-travix

  integration-test-start-upstream:
    services:
    - name: upstream
      image: estafette/estafette-ci-web:0.1.634
      readiness:
        path: /robots.txt
        port: 5000

  integration-test-start-sidecar:
    services:
    - name: myservice.mynamespace.svc.cluster.local
      image: europe-docker.pkg.dev/travix-com/eu-docker-travix/openresty-sidecar:${ESTAFETTE_BUILD_VERSION}
      env:
        SERVICE_NAME: myservice
        NAMESPACE: mynamespace
        OFFLOAD_TO_HOST: upstream
        OFFLOAD_TO_PORT: 5000
        OFFLOAD_TO_PROTO: http
        ENFORCE_HTTPS: false
        GRACEFUL_SHUTDOWN_DELAY_SECONDS: 3
      readiness:
        path: /robots.txt
        port: 80
    image: alpine:3.10
    commands:
    - apk add curl
    - curl --retry 5 --fail http://myservice.mynamespace.svc.cluster.local/robots.txt

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - europe-docker.pkg.dev/travix-com/eu-docker-travix
    tags:
    - ${ESTAFETTE_GIT_BRANCH}

releases:
  windows:
    builder:
      os: windows
    clone: true
    stages:
      bake:
        image: extensions/docker:windowsservercore-ltsc2019
        action: build
        no-cache: true
        expand-variables: false
        container: git-clone
        repositories:
        - europe-docker.pkg.dev/travix-com/eu-docker-travix
        dockerfile: Dockerfile.windowsservercore-ltsc2019

      push-to-docker-hub:
        image: extensions/docker:windowsservercore-ltsc2019
        action: push
        container: git-clone
        repositories:
        - europe-docker.pkg.dev/travix-com/eu-docker-travix
        tags:
        - ${ESTAFETTE_GIT_BRANCH}-windowsservercore-ltsc2019
        pushVersionTag: false
