# Dockerfile - Windows
# https://github.com/openresty/docker-openresty

ARG RESTY_INSTALL_BASE="microsoft/windowsservercore"
ARG RESTY_INSTALL_TAG="ltsc2019"

FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS downloader

ARG RESTY_VERSION="1.15.8.1"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR C:/dl

# Download Perl and OpenResty
RUN Invoke-WebRequest -Uri "https://chocolatey.org/install.ps1" -UseBasicParsing | iex ; \
    choco install strawberryperl -y --no-progress ; \
    mv C:\Strawberry\ C:\dl\ ; \
    Write-Host "Downloading OpenResty.." ; \
    Invoke-WebRequest "https://openresty.org/download/openresty-$($env:RESTY_VERSION)-win64.zip" -OutFile C:\openresty.zip ; \
    Expand-Archive C:\openresty.zip . ; \
    mv .\openresty-*\ .\openresty ; 


FROM mcr.microsoft.com/windows/servercore:ltsc2019

ARG RESTY_INSTALL_BASE="microsoft/windowsservercore"
ARG RESTY_INSTALL_TAG="ltsc2019"
ARG RESTY_VERSION="1.15.8.2"

LABEL resty_install_base="${RESTY_INSTALL_BASE}"
LABEL resty_install_tag="${RESTY_INSTALL_TAG}"
LABEL resty_version="${RESTY_VERSION}"

WORKDIR C:/openresty
RUN setx /M PATH "%PATH%;C:\Strawberry\perl\bin;C:\openresty"

CMD [ "nginx", "-g", "\"daemon off;\""]

COPY --from=downloader C:/dl/ C:/

# nginx config is not overwritten as paths in the Windows distribution are already fine

# we do not move writeable temp paths for Windows (#119)