service_name: openresty-sidecar
disabled: false
sampler:
    type: ${JAEGER_SAMPLER_TYPE}
    param: ${JAEGER_SAMPLER_PARAM}
reporter:
    logSpans: ${JAEGER_REPORTER_LOG_SPANS}
    localAgentHostPort: ${JAEGER_AGENT_HOST}:${JAEGER_AGENT_PORT}
headers:
    jaegerDebugHeader: jaeger-debug-id
    jaegerBaggageHeader: jaeger-baggage
    TraceContextHeaderName: uber-trace-id
    traceBaggageHeaderPrefix: "uberctx-"
baggage_restrictions:
    denyBaggageOnInitializationFailure: false
    hostPort: ${JAEGER_AGENT_HOST}:5778
    refreshInterval: 60