service_name: ${SERVICE_NAME}
disabled: false
sampler:
  type: ${JAEGER_SAMPLER_TYPE}
  param: ${JAEGER_SAMPLER_PARAM}
  samplingServerURL: http://${JAEGER_AGENT_HOST}:5778/sampling
reporter:
  logSpans: ${JAEGER_REPORTER_LOG_SPANS}
  localAgentHostPort: ${JAEGER_AGENT_HOST}:${JAEGER_AGENT_PORT}
baggage_restrictions:
  denyBaggageOnInitializationFailure: false
  hostPort: ${JAEGER_AGENT_HOST}:5778